# Generated by Django 2.1.7 on 2019-02-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190223_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsection',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='product',
            name='extra_large_size',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='large_size',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='medium_size',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='small_size',
            field=models.BooleanField(default=False),
        ),
    ]
